#!/usr/bin/env tsx
/*
 * metadata.ts
 *
 * Deterministic metadata helper for EMS .emtour files.
 *
 * v0.3 scope:
 *   - generate metadata YAML from one .emtour file
 *   - validate an existing generated metadata file against current .emtour/source files
 *   - update is currently generate with overwrite semantics
 *   - compact tour IDs: generate 102 01 or generate 102_01
 *   - robust JSON/YAML quoted-string decoding for validate
 *   - intended location: tours/.scripts/metadata.ts
 *
 * No third-party dependencies. Run with:
 *   npx tsx ../tours/.scripts/metadata.ts generate 102 01
 *   npx tsx ../tours/.scripts/metadata.ts validate 102_01
 *   npx tsx ../tours/.scripts/metadata.ts update tours/102_CoreMark/01_Introduction.emtour
 */

import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

type Cmd = string;

type Step = {
  index: number;
  cmds: Cmd[];
  focus?: [number, number];
  acts: string[];
  text: string;
  heading?: string;
  icon?: string;
};

type TourFile = {
  title: string;
  files: string[];
  steps: Step[];
};

type ResolvedFile = {
  index: number;
  raw: string;
  resolved: string;
  absPath: string;
  kind: "source" | "asset" | "image" | "other";
  exists: boolean;
};

type MarkerAudit = {
  stop: number;
  file_index: number;
  file_raw: string;
  file_resolved: string;
  label: string;
  line: number;
  expect: string;
  context_before: string[];
  context_after: string[];
  status: "ok" | "missing_file" | "line_out_of_range" | "not_source";
};

type ParsedIds = {
  groupId: string;
  tourNumber: string;
  tourId: string;
  groupDir: string;
};

const MECHANICAL_HEADER = "# Generated by metadata.ts. Mechanical fields may be refreshed by update.";

function usage(exitCode = 1): never {
  const msg = `Usage:
  npx tsx ../tours/.scripts/metadata.ts generate <path/to/Tour.emtour> [--out <metadata.yml>]
  npx tsx ../tours/.scripts/metadata.ts update   <path/to/Tour.emtour> [--out <metadata.yml>]
  npx tsx ../tours/.scripts/metadata.ts validate <path/to/Tour.emtour> [--metadata <metadata.yml>]

  npx tsx ../tours/.scripts/metadata.ts generate <group> <tour>
  npx tsx ../tours/.scripts/metadata.ts validate <group> <tour>
  npx tsx ../tours/.scripts/metadata.ts generate <group>_<tour>

Examples from emporium/workspace:
  npx tsx ../tours/.scripts/metadata.ts generate 102 01
  npx tsx ../tours/.scripts/metadata.ts validate 102_01

Notes:
  - generate/update write metadata; validate never writes.
  - output path defaults to ../tours/.metadata/<group>_<tour>.yml.
  - run from emporium/workspace for normal EMS source resolution.
  - .asset/.assets refs resolve under tours/, source refs resolve under workspace/ with ':' -> '/'.`;
  console.error(msg);
  process.exit(exitCode);
}

function readText(file: string): string {
  return fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");
}

function findToursRoot(fromFile: string): string {
  let dir = path.resolve(path.dirname(fromFile));
  while (true) {
    if (path.basename(dir) === "tours") return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: if user runs from workspace root and passed a relative tours/... path.
  const cwdTours = path.resolve(process.cwd(), "tours");
  if (fs.existsSync(cwdTours) && fs.statSync(cwdTours).isDirectory()) return cwdTours;
  throw new Error(`Could not locate tours root from ${fromFile}`);
}

function repoRootFor(toursRoot: string): string {
  return path.dirname(toursRoot);
}

function workspaceRootFor(toursRoot: string): string {
  const repoRoot = repoRootFor(toursRoot);
  const nested = path.join(repoRoot, "workspace");
  if (fs.existsSync(nested) && fs.statSync(nested).isDirectory()) return nested;
  return repoRoot;
}

function findToursRootFromCwd(): string {
  const candidates = [
    path.resolve(process.cwd(), "tours"),
    path.resolve(process.cwd(), "..", "tours"),
  ];
  for (const c of candidates) {
    if (fs.existsSync(c) && fs.statSync(c).isDirectory()) return c;
  }
  throw new Error(`Could not locate tours root from cwd ${process.cwd()}`);
}

function resolveTourById(groupId: string, tourNumber: string): string {
  const toursRoot = findToursRootFromCwd();
  const groups = fs.readdirSync(toursRoot, { withFileTypes: true })
    .filter(d => d.isDirectory() && d.name.startsWith(`${groupId}_`))
    .map(d => d.name);
  if (groups.length !== 1) throw new Error(`Expected exactly one tour group starting ${groupId}_ under ${toursRoot}; found ${groups.length}`);
  const groupDir = path.join(toursRoot, groups[0]);
  const tours = fs.readdirSync(groupDir, { withFileTypes: true })
    .filter(d => d.isFile() && d.name.startsWith(`${tourNumber}_`) && d.name.endsWith(".emtour"))
    .map(d => d.name);
  if (tours.length !== 1) throw new Error(`Expected exactly one .emtour starting ${tourNumber}_ under ${groupDir}; found ${tours.length}`);
  return path.join(groupDir, tours[0]);
}

function parseIds(emtourPath: string, toursRoot: string): ParsedIds {
  const abs = path.resolve(emtourPath);
  const rel = slash(path.relative(toursRoot, abs));
  const parts = rel.split("/");
  if (parts.length < 2) throw new Error(`Expected tour inside tours/<group>/<tour>.emtour: ${rel}`);
  const groupDir = parts[0];
  const fileName = path.basename(parts[parts.length - 1]);
  const gm = groupDir.match(/^(\d{3})_/);
  const tm = fileName.match(/^(\d{2})_/);
  if (!gm || !tm) throw new Error(`Could not infer group/tour id from ${rel}`);
  return { groupId: gm[1], tourNumber: tm[1], tourId: `${gm[1]}_${tm[1]}`, groupDir };
}

function defaultMetadataPath(emtourPath: string): string {
  const toursRoot = findToursRoot(emtourPath);
  const ids = parseIds(emtourPath, toursRoot);
  return path.join(toursRoot, ".metadata", `${ids.tourId}.yml`);
}

function parseArgs(argv: string[]) {
  const cmd = argv[0];
  if (!cmd || !["generate", "update", "validate"].includes(cmd)) usage();

  let pos = 1;
  let tourPath: string | undefined;
  const a = argv[pos];
  const b = argv[pos + 1];

  if (a && /^\d{3}$/.test(a) && b && /^\d{2}$/.test(b)) {
    tourPath = resolveTourById(a, b);
    pos += 2;
  } else if (a && /^\d{3}_\d{2}$/.test(a)) {
    const [g, t] = a.split("_");
    tourPath = resolveTourById(g, t);
    pos += 1;
  } else if (a) {
    tourPath = a;
    pos += 1;
  } else {
    usage();
  }

  let out: string | undefined;
  let metadata: string | undefined;
  const rest = argv.slice(pos);
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === "--out") out = rest[++i];
    else if (rest[i] === "--metadata" || rest[i] === "-m") metadata = rest[++i];
    else usage();
  }
  return { cmd, tourPath, out, metadata };
}

function parseScalar(line: string, key: string): string | undefined {
  const re = new RegExp(`^${key}:\\s*(.*)$`);
  const m = line.match(re);
  if (!m) return undefined;
  return stripQuotes(m[1].trim());
}

function stripQuotes(s: string): string {
  const t = s.trim();

  // metadata.ts emits strings using JSON.stringify(), which is valid YAML.
  // Decode those strings with JSON.parse() so escaped quotes/backslashes compare
  // against source text correctly during validate.
  if (t.startsWith('"') && t.endsWith('"')) {
    try {
      return JSON.parse(t);
    } catch {
      return t.slice(1, -1);
    }
  }

  if (t.startsWith("'") && t.endsWith("'")) {
    return t.slice(1, -1).replace(/''/g, "'");
  }

  return t;
}

function parseInlineList(s: string): string[] {
  const m = s.match(/\[(.*)\]/);
  if (!m) return [];
  const body = m[1].trim();
  if (!body) return [];
  return body.split(",").map(x => stripQuotes(x.trim())).filter(Boolean);
}

function parseFocus(s: string): [number, number] | undefined {
  const vals = parseInlineList(s).map(Number);
  if (vals.length === 2 && vals.every(Number.isFinite)) return [vals[0], vals[1]];
  return undefined;
}

function parseTour(emtourPath: string): TourFile {
  const text = readText(emtourPath);
  const lines = text.split("\n");
  let title = "";
  const files: string[] = [];
  const steps: Step[] = [];

  let mode: "root" | "files" | "steps" | "cmds" | "text" = "root";
  let current: Step | undefined;
  let textIndent = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      if (mode === "text" && current) current.text += "\n";
      continue;
    }

    const topTitle = parseScalar(line, "title");
    if (!title && topTitle !== undefined) {
      title = topTitle;
      continue;
    }

    if (/^files:\s*$/.test(trimmed)) { mode = "files"; continue; }
    if (/^steps:\s*$/.test(trimmed)) { mode = "steps"; continue; }

    if (mode === "files") {
      const m = line.match(/^\s*-\s+(.+)$/);
      if (m) {
        files.push(stripQuotes(m[1].trim()));
        continue;
      }
      if (/^\S/.test(line)) mode = "root";
    }

    const stepStart = line.match(/^\s*-\s+cmds:\s*$/);
    if (mode === "steps" || mode === "cmds" || mode === "text") {
      if (stepStart) {
        current = { index: steps.length + 1, cmds: [], acts: [], text: "" };
        steps.push(current);
        mode = "cmds";
        continue;
      }
    }

    if (!current) continue;

    if (mode === "cmds") {
      const cmdM = line.match(/^\s*-\s+(.+)$/);
      if (cmdM) {
        current.cmds.push(stripQuotes(cmdM[1].trim()));
        continue;
      }
    }

    const focusM = line.match(/^\s*focus:\s*(\[.*\])\s*$/);
    if (focusM) {
      current.focus = parseFocus(focusM[1]);
      mode = "steps";
      continue;
    }

    const actsM = line.match(/^\s*acts:\s*(\[.*\])\s*$/);
    if (actsM) {
      current.acts = parseInlineList(actsM[1]);
      mode = "steps";
      continue;
    }

    const textM = line.match(/^(\s*)text:\s*\|\s*$/);
    if (textM) {
      mode = "text";
      textIndent = textM[1].length + 2;
      continue;
    }

    if (mode === "text") {
      if (stepStart) {
        // Unreachable because handled above; kept for clarity.
        continue;
      }
      const leading = line.match(/^\s*/)?.[0].length ?? 0;
      if (leading < textIndent && /^\s*-\s+cmds:\s*$/.test(line)) {
        i--;
        mode = "steps";
        continue;
      }
      const cut = Math.min(textIndent, leading);
      current.text += line.slice(cut) + "\n";
    }
  }

  for (const step of steps) {
    const h = extractHeading(step.text);
    if (h) { step.icon = h.icon; step.heading = h.heading; }
  }

  if (!title) throw new Error(`No title found in ${emtourPath}`);
  return { title, files, steps };
}

function extractHeading(text: string): { icon: string; heading: string } | undefined {
  const m = text.match(/\{\[ht,([^\]]+)\]([^\n{}]+)/);
  if (!m) return undefined;
  return { icon: m[1].trim(), heading: htmlToText(m[2].trim()) };
}

function htmlToText(s: string): string {
  return s
    .replace(/<[^>]*>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&thinsp;/g, " ")
    .replace(/&ndash;/g, "–")
    .replace(/&mdash;/g, "—")
    .replace(/&bull;/g, "•")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .trim();
}

function slash(p: string): string {
  return p.replace(/\\/g, "/");
}

function resolveTourRef(workspaceRoot: string, toursRoot: string, repoRoot: string, raw: string): { absPath: string; resolved: string; kind: ResolvedFile["kind"] } {
  const kind = classifyFile(raw);
  if (raw.startsWith(".")) {
    const absPath = path.resolve(toursRoot, raw);
    return { absPath, resolved: slash(path.relative(repoRoot, absPath)), kind };
  }
  const translated = raw.replace(/:/g, "/");
  const absPath = path.resolve(workspaceRoot, translated);
  return { absPath, resolved: slash(path.relative(workspaceRoot, absPath)), kind };
}

function classifyFile(raw: string): ResolvedFile["kind"] {
  const lower = raw.toLowerCase();
  if (lower.match(/\.(png|jpg|jpeg|gif|svg|webp)$/)) return "image";
  if (raw.startsWith(".assets/") || raw.startsWith("./.assets/") || raw.includes("/.assets/")) return "asset";
  if (lower.match(/\.(em\.ts|ts|c|cpp|h|hpp|md|ld)$/)) return "source";
  return "other";
}

function resolvedFiles(tour: TourFile, workspaceRoot: string, toursRoot: string, repoRoot: string): ResolvedFile[] {
  return tour.files.map((raw, i) => {
    const r = resolveTourRef(workspaceRoot, toursRoot, repoRoot, raw);
    return { index: i + 1, raw, resolved: r.resolved, absPath: r.absPath, kind: r.kind, exists: fs.existsSync(r.absPath) };
  });
}

function gitSha(cwd: string): string {
  try {
    return execSync("git rev-parse HEAD", { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "unknown";
  }
}

function markerCommands(step: Step): Array<{ fileIndex: number; label: string; line: number; raw: string }> {
  const out: Array<{ fileIndex: number; label: string; line: number; raw: string }> = [];
  for (const cmd of step.cmds) {
    const m = cmd.match(/^mark\s+(\d+)\s+([A-Za-z][A-Za-z0-9_-]*)\s+(\d+)$/);
    if (m) out.push({ fileIndex: Number(m[1]), label: m[2], line: Number(m[3]), raw: cmd });
  }
  return out;
}

function buildMarkerAudit(tour: TourFile, rfiles: ResolvedFile[]): MarkerAudit[] {
  const audit: MarkerAudit[] = [];
  for (const step of tour.steps) {
    for (const mark of markerCommands(step)) {
      const rf = rfiles[mark.fileIndex - 1];
      if (!rf) {
        audit.push({ stop: step.index, file_index: mark.fileIndex, file_raw: "", file_resolved: "", label: mark.label, line: mark.line, expect: "", context_before: [], context_after: [], status: "missing_file" });
        continue;
      }
      if (!rf.exists) {
        audit.push({ stop: step.index, file_index: mark.fileIndex, file_raw: rf.raw, file_resolved: rf.resolved, label: mark.label, line: mark.line, expect: "", context_before: [], context_after: [], status: "missing_file" });
        continue;
      }
      if (rf.kind !== "source" && rf.kind !== "other") {
        audit.push({ stop: step.index, file_index: mark.fileIndex, file_raw: rf.raw, file_resolved: rf.resolved, label: mark.label, line: mark.line, expect: "", context_before: [], context_after: [], status: "not_source" });
        continue;
      }
      const srcLines = readText(rf.absPath).split("\n");
      const idx = mark.line - 1;
      if (idx < 0 || idx >= srcLines.length) {
        audit.push({ stop: step.index, file_index: mark.fileIndex, file_raw: rf.raw, file_resolved: rf.resolved, label: mark.label, line: mark.line, expect: "", context_before: [], context_after: [], status: "line_out_of_range" });
        continue;
      }
      audit.push({
        stop: step.index,
        file_index: mark.fileIndex,
        file_raw: rf.raw,
        file_resolved: rf.resolved,
        label: mark.label,
        line: mark.line,
        expect: srcLines[idx].trimEnd(),
        context_before: srcLines.slice(Math.max(0, idx - 3), idx).map(s => s.trimEnd()),
        context_after: srcLines.slice(idx + 1, Math.min(srcLines.length, idx + 4)).map(s => s.trimEnd()),
        status: "ok",
      });
    }
  }
  return audit;
}

function macroUsage(tour: TourFile) {
  const macros = new Map<string, number>();
  const headingIcons: string[] = [];
  const commands = new Map<string, number>();
  const actions = new Set<string>();

  for (const step of tour.steps) {
    if (step.icon) headingIcons.push(step.icon);
    for (const act of step.acts) actions.add(act);
    for (const cmd of step.cmds) {
      const name = cmd.split(/\s+/)[0];
      commands.set(name, (commands.get(name) ?? 0) + 1);
    }
    for (const m of step.text.matchAll(/\{\[([a-z][a-z])(?:,|\])/g)) {
      const name = m[1];
      macros.set(name, (macros.get(name) ?? 0) + 1);
    }
  }

  return { macros, headingIcons, commands, actions: Array.from(actions).sort() };
}

function yq(s: string): string {
  // JSON string syntax is valid YAML and avoids many escaping surprises.
  return JSON.stringify(s);
}

function yamlList(items: string[], indent: string): string {
  if (!items.length) return `${indent}[]\n`;
  return items.map(x => `${indent}- ${yq(x)}\n`).join("");
}

function mapToYaml(map: Map<string, number>, indent: string): string {
  if (!map.size) return `${indent}{}\n`;
  return Array.from(map.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${indent}${yq(k)}: ${v}\n`).join("");
}

function metadataYaml(emtourPath: string, tour: TourFile, rfiles: ResolvedFile[], audit: MarkerAudit[], workspaceRoot: string, toursRoot: string): string {
  const ids = parseIds(emtourPath, toursRoot);
  const repoRoot = repoRootFor(toursRoot);
  const relTour = slash(path.relative(repoRoot, path.resolve(emtourPath)));
  const usage = macroUsage(tour);
  const now = new Date().toISOString();
  let y = "";
  y += `${MECHANICAL_HEADER}\n`;
  y += `schema_version: 0.1\n`;
  y += `tour_id: ${yq(ids.tourId)}\n`;
  y += `group_id: ${yq(ids.groupId)}\n`;
  y += `tour_number: ${yq(ids.tourNumber)}\n`;
  y += `source_file: ${yq(relTour)}\n`;
  y += `title: ${yq(tour.title)}\n`;
  y += `\nsource_snapshot:\n`;
  y += `  git_sha: ${yq(gitSha(workspaceRoot))}\n`;
  y += `  generated_at: ${yq(now)}\n`;
  y += `\nground_truth:\n`;
  y += `  stop_count: ${tour.steps.length}\n`;
  y += `  files:\n`;
  for (const f of rfiles) {
    y += `    - index: ${f.index}\n`;
    y += `      raw: ${yq(f.raw)}\n`;
    y += `      resolved: ${yq(f.resolved)}\n`;
    y += `      kind: ${yq(f.kind)}\n`;
    y += `      exists: ${f.exists}\n`;
  }

  y += `\nsteps:\n`;
  for (const s of tour.steps) {
    y += `  - stop: ${s.index}\n`;
    y += `    heading: ${yq(s.heading ?? "")}\n`;
    y += `    icon: ${yq(s.icon ?? "")}\n`;
    y += `    cmds:\n`;
    y += yamlList(s.cmds, "      ");
    if (s.focus) y += `    focus: [${s.focus[0]}, ${s.focus[1]}]\n`;
    else y += `    focus: []\n`;
    y += `    acts:\n`;
    y += yamlList(s.acts, "      ");
  }

  y += `\nmarker_audit:\n`;
  if (!audit.length) y += `  []\n`;
  for (const a of audit) {
    y += `  - stop: ${a.stop}\n`;
    y += `    file_index: ${a.file_index}\n`;
    y += `    file_raw: ${yq(a.file_raw)}\n`;
    y += `    file_resolved: ${yq(a.file_resolved)}\n`;
    y += `    label: ${yq(a.label)}\n`;
    y += `    line: ${a.line}\n`;
    y += `    expect: ${yq(a.expect)}\n`;
    y += `    context_before:\n`;
    y += yamlList(a.context_before, "      ");
    y += `    context_after:\n`;
    y += yamlList(a.context_after, "      ");
    y += `    status: ${yq(a.status)}\n`;
  }

  y += `\nusage:\n`;
  y += `  heading_icons:\n`;
  y += yamlList(usage.headingIcons, "    ");
  y += `  macros:\n`;
  y += mapToYaml(usage.macros, "    ");
  y += `  commands:\n`;
  y += mapToYaml(usage.commands, "    ");
  y += `  actions:\n`;
  y += yamlList(usage.actions, "    ");

  y += `\ncurated:\n`;
  y += `  summary: ""\n`;
  y += `  learning_objectives: []\n`;
  y += `  concepts_introduced: []\n`;
  y += `  concepts_reinforced: []\n`;
  y += `  prerequisites: []\n`;
  y += `  prepares_for: []\n`;
  y += `  notes: ""\n`;
  return y;
}

function parseGeneratedMetadataMarkers(metaText: string): MarkerAudit[] {
  const lines = metaText.split("\n");
  const markers: MarkerAudit[] = [];
  let inMarker = false;
  let current: any = undefined;
  for (const line of lines) {
    if (line.startsWith("marker_audit:")) { inMarker = true; continue; }
    if (inMarker && /^\S/.test(line) && !line.startsWith("marker_audit:")) break;
    if (!inMarker) continue;
    const start = line.match(/^\s*-\s+stop:\s+(\d+)/);
    if (start) {
      if (current) markers.push(current as MarkerAudit);
      current = { stop: Number(start[1]), context_before: [], context_after: [] };
      continue;
    }
    if (!current) continue;
    const kv = line.match(/^\s+([a-z_]+):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    const val = stripQuotes(kv[2].trim());
    if (["file_index", "line"].includes(key)) current[key] = Number(val);
    else if (["file_raw", "file_resolved", "label", "expect", "status"].includes(key)) current[key] = val;
  }
  if (current) markers.push(current as MarkerAudit);
  return markers;
}

function validate(emtourPath: string, metaPath: string): number {
  const toursRoot = findToursRoot(emtourPath);
  const workspaceRoot = workspaceRootFor(toursRoot);
  const repoRoot = repoRootFor(toursRoot);
  const tour = parseTour(emtourPath);
  const rfiles = resolvedFiles(tour, workspaceRoot, toursRoot, repoRoot);
  const current = buildMarkerAudit(tour, rfiles);
  if (!fs.existsSync(metaPath)) {
    console.error(`FAIL metadata file not found: ${metaPath}`);
    return 2;
  }
  const meta = readText(metaPath);
  let failures = 0;
  let warnings = 0;

  const stopCountM = meta.match(/ground_truth:\n(?:.*\n)*?\s+stop_count:\s+(\d+)/);
  if (stopCountM && Number(stopCountM[1]) === tour.steps.length) console.log(`OK   stop count ${tour.steps.length}`);
  else { console.log(`FAIL stop count metadata=${stopCountM?.[1] ?? "missing"} current=${tour.steps.length}`); failures++; }

  const metaMarkers = parseGeneratedMetadataMarkers(meta);
  const byKey = new Map<string, MarkerAudit>();
  for (const m of metaMarkers) byKey.set(`${m.stop}:${m.file_index}:${m.label}`, m);

  for (const cur of current) {
    const key = `${cur.stop}:${cur.file_index}:${cur.label}`;
    const old = byKey.get(key);
    if (!old) { console.log(`WARN marker ${key} missing from metadata`); warnings++; continue; }
    if (cur.status !== "ok") { console.log(`FAIL marker ${key} current status=${cur.status}`); failures++; continue; }
    if (old.expect === cur.expect) {
      console.log(`OK   marker ${key} line ${cur.line}`);
    } else {
      const rf = rfiles[cur.file_index - 1];
      const moved = findTextLine(rf?.absPath, old.expect);
      if (moved && moved !== old.line) {
        console.log(`WARN marker ${key} expected text moved: metadata line ${old.line}, found line ${moved}`);
        warnings++;
      } else {
        console.log(`FAIL marker ${key} expected text mismatch at line ${cur.line}`);
        failures++;
      }
    }
  }

  for (const f of rfiles) {
    if (f.exists) console.log(`OK   file ${f.index}: ${f.resolved}`);
    else { console.log(`FAIL file ${f.index} missing: ${f.resolved}`); failures++; }
  }

  console.log(`\nvalidate: ${failures} fail, ${warnings} warn`);
  return failures ? 2 : warnings ? 1 : 0;
}

function findTextLine(absPath: string | undefined, text: string | undefined): number | undefined {
  if (!absPath || !text || !fs.existsSync(absPath)) return undefined;
  const lines = readText(absPath).split("\n");
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].trimEnd() === text) return i + 1;
  }
  return undefined;
}

function writeGenerated(emtourPath: string, outPath: string) {
  const toursRoot = findToursRoot(emtourPath);
  const workspaceRoot = workspaceRootFor(toursRoot);
  const repoRoot = repoRootFor(toursRoot);
  const tour = parseTour(emtourPath);
  const rfiles = resolvedFiles(tour, workspaceRoot, toursRoot, repoRoot);
  const audit = buildMarkerAudit(tour, rfiles);
  const yaml = metadataYaml(emtourPath, tour, rfiles, audit, workspaceRoot, toursRoot);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, yaml, "utf8");
  console.log(`wrote ${slash(path.relative(process.cwd(), outPath))}`);
  console.log(`tour ${parseIds(emtourPath, toursRoot).tourId}: ${tour.steps.length} stops, ${tour.files.length} files, ${audit.length} markers`);
}

function main() {
  const { cmd, tourPath, out, metadata } = parseArgs(process.argv.slice(2));
  const absTour = path.resolve(tourPath);
  if (!fs.existsSync(absTour)) throw new Error(`Tour file not found: ${absTour}`);
  const metaPath = path.resolve(out ?? metadata ?? defaultMetadataPath(absTour));

  if (cmd === "generate" || cmd === "update") {
    writeGenerated(absTour, metaPath);
    return;
  }
  if (cmd === "validate") {
    process.exitCode = validate(absTour, metaPath);
    return;
  }
  usage();
}

try {
  main();
} catch (e: any) {
  console.error(`ERROR: ${e.message ?? e}`);
  process.exit(2);
}
